[Appearance]
standard_dialogs=xdgdesktopportal
custom_palette=true
style=kvantum
icon_theme=Sweet-Purple
color_scheme_path=/home/chihin/.config/qt6ct/colors/CosmicDark.conf

[Interface]
double_click_interval=650
