background = 0xC8210E33
base = 0xE63B2E4D
text = 0xFFF2A1FF
alternate_base = 0xE60E1830
bright_text = 0xFFE0265E
accent = 0xFF00A6FF
accent_secondary = 0xFF0285CC
h1_size = 24
h2_size = 18
h3_size = 14
font_size = 12
small_font_size = 10
font_family = Inter
font_family_monospace = JetBrainsMono Nerd Font
